        // ==================== CONFIG ====================
        const CONFIG = {
            API_URL: 'https://silent-block-bedf.ahmedrabieharoun.workers.dev',
            BOT_USERNAME: '@Crystal_Ranch_bot',
            DEPOSIT_WALLET: 'UQAzGsppYQfQwVnVVQDt2Jq9r4cm7fO3iVuLCxv30FixJq1-',
            PRODUCTION_INTERVAL: 60000,
            MARKET_REFRESH: 15000,
            DEPOSIT_VERIFY_INTERVAL: 10000,
            CSRF_TOKEN: null, // fetched dynamically from server on startup
            CSRF_REFRESH_INTERVAL: 55000, // refresh every 55 seconds
            CRYSTAL_PRICE: 25,
            TASK_REWARD: 0.001,
            MAX_ACTIVE_ORDERS: 2,
            COW_LEVELS: {
                1: { productionPerDay: 500, activationCost: 200, upgradeCost: 6000, duration: 86400 },
                2: { productionPerDay: 1000, activationCost: 350, upgradeCost: 20000, duration: 86400 },
                3: { productionPerDay: 2500, activationCost: 1200, upgradeCost: 0, duration: 86400 }
            },
            STORAGE_LEVELS: {
                1: { capacity: 2000, cost: 0 },
                2: { capacity: 5000, cost: 2000 },
                3: { capacity: 10000, cost: 5000 },
                4: { capacity: 20000, cost: 10000 },
                5: { capacity: 40000, cost: 20000 },
                6: { capacity: 80000, cost: 40000 },
                7: { capacity: 160000, cost: 80000 },
                8: { capacity: 320000, cost: 160000 },
                9: { capacity: 640000, cost: 320000 },
                10: { capacity: 1000000, cost: 600000 }
            }
        };

        // ==================== TRANSLATIONS ====================
        const TRANSLATIONS = {
            en: {
                'nav.farm': 'Farm',
                'nav.market': 'Market',
                'nav.crystal': 'Crystal',
                'nav.friends': 'Friends',
                'nav.tasks': 'Tasks',
                'nav.profile': 'Profile',
                'status.milk': 'MILK',
                'status.eggs': 'EGGS',
                'status.crystal': 'CRYSTAL',
                'status.deposit': 'Deposit',
                'farm.cow.name': 'Cow',
                'farm.chicken.name': 'Chicken',
                'farm.crystal.name': 'Crystal Engine',
                'farm.prod': 'Prod',
                'farm.owned': 'Owned',
                'farm.supply': 'Supply',
                'farm.buy': 'Buy Multiple',
                'farm.hatch': 'Hatch',
                'farm.start': 'Start',
                'farm.yield': 'Yield',
                'market.title': 'P2P Market',
                'market.buy': 'Buy',
                'market.myOrders': 'My Orders',
                'market.milk': 'Milk',
                'market.eggs': 'Eggs',
                'market.totalOrders': 'Total Orders',
                'market.milkQty': 'Milk',
                'market.eggsQty': 'Eggs',
                'market.bestPrice': 'Best Price',
                'market.createSell': 'Create Sell Order',
                'market.refresh': 'Refresh',
                'market.loadMore': 'Show More',
                'market.noOrders': 'No active sell orders',
                'market.activeOrders': 'Active Orders',
                'market.history': 'History',
                'crystal.title': 'Crystal Conversion',
                'crystal.perTon': 'TON per Crystal',
                'crystal.yourCrystals': 'Your Crystals',
                'crystal.youReceive': 'You Receive',
                'crystal.convert': 'Convert',
                'crystal.milkAvailable': 'Milk available',
                'crystal.eggsAvailable': 'Eggs available',
                'referral.title': 'Referral Program',
                'referral.description': 'Earn 10% commission when your friends buy machines with TON!',
                'referral.share': 'Share this link with friends',
                'referral.friends': 'Friends',
                'referral.claim': 'Claim Earnings',
                'referral.recent': 'Recent Referrals',
                'referral.noReferrals': 'No referrals yet',
                'referral.earningsHistory': 'Earnings History',
                'referral.noEarnings': 'No earnings yet',
                'tasks.title': 'Tasks & Rewards',
                'tasks.partner': 'Partner Tasks',
                'tasks.community': 'Community Tasks',
                'tasks.addTask': 'Add Task',
                'tasks.refresh': 'Refresh',
                'tasks.noTasks': 'No tasks available',
                'tasks.taskType': 'Task Type',
                'tasks.channel': 'Channel',
                'tasks.bot': 'Bot',
                'tasks.channelNote': '⚠️ Bot must be admin in the channel for verification to work!',
                'tasks.link': 'Link',
                'tasks.targetUsers': 'Target Users (min 100)',
                'tasks.rewardPerUser': 'Reward Per User (TON)',
                'tasks.rewardFixed': 'Fixed at 0.001 TON per completion',
                'tasks.yourBalance': 'Your Balance',
                'tasks.confirm': 'Confirm & Pay',
                'tasks.verify': 'Task Verification',
                'tasks.join': 'Join',
                'tasks.check': 'Verify & Claim',
                'tasks.reward': 'Reward',
                'profile.totalMachines': 'Total Machines',
                'profile.production': 'Production',
                'profile.assets': 'Assets',
                'profile.balance': 'Balance',
                'profile.withdraw': 'Withdraw TON',
                'profile.withdrawAmount': 'Amount (min 0.1 TON)',
                'profile.withdrawAddress': 'TON Wallet Address',
                'profile.fee': 'Fee (5%)',
                'profile.youReceive': 'You receive',
                'profile.withdrawBtn': 'Withdraw',
                'modal.sell.title': 'Sell Order',
                'modal.sell.resource': 'Resource',
                'modal.sell.quantity': 'Quantity (min 100)',
                'modal.sell.place': 'Place Sell Order',
                'modal.confirm.title': 'Confirm Purchase',
                'modal.confirm.package': 'Milk Package',
                'modal.confirm.cancel': 'Cancel',
                'modal.confirm.confirm': 'Confirm & Pay',
                'modal.hatch.title': 'Hatch Machine',
                'modal.hatch.cowCost': '50,000 Milk',
                'modal.hatch.chickenCost': '5,000 Eggs',
                'modal.hatch.hatchBtn': 'Hatch',
                'modal.deposit.title': 'Deposit TON',
                'modal.deposit.wallet': 'Wallet',
                'modal.deposit.notConnected': 'Not connected',
                'modal.deposit.connect': 'Connect',
                'modal.deposit.important': 'IMPORTANT:',
                'modal.deposit.warning': 'Your User ID',
                'modal.deposit.mustBeComment': 'must be the ONLY comment',
                'modal.deposit.amount': 'Amount (TON)',
                'modal.deposit.submit': 'Deposit TON',
                'modal.deposit.processing': 'Processing deposit...',
                'help.title': 'How to Play',
                'help.cow.title': 'Cow Machine',
                'help.cow.desc': '1 TON · 41 Milk/h<br>Global cap: 1000<br>Hatch: 50,000 Milk = 1 Cow',
                'help.chicken.title': 'Chicken Machine',
                'help.chicken.desc': '1 TON · 41 Eggs/h<br>Unlocks after all Cows sold',
                'help.crystal.title': 'Crystal Engine',
                'help.crystal.desc': '20 TON · 20k Milk + 20k Eggs = 1 Crystal<br>Convert Crystals → TON',
                'help.hatch.title': 'Hatch System',
                'help.hatch.desc': '50,000 Milk = 1 Cow<br>5,000 Eggs = 1 Chicken<br>No global cap limit',
                'help.market.title': 'P2P Market',
                'help.market.desc': 'Trade Milk & Eggs with other players',
                'help.referral.title': 'Referral',
                'help.referral.desc': 'Earn 10% of every TON purchase made by your friends',
                'help.tasks.title': 'Tasks & Rewards',
                'help.tasks.desc': 'Complete tasks to earn 0.001 TON<br>Create your own community tasks (min 100 users)',
                'help.leaderboard.title': 'Leaderboard Competition',
                'help.leaderboard.desc': '1 new cow = 10 points · Top 20 win 150 TON total<br>Ends when 1000 cows sold<br>⚠️ You must buy a cow to appear on leaderboard!'
            },
            ru: {
                'nav.farm': 'Ферма',
                'nav.market': 'Рынок',
                'nav.crystal': 'Кристалл',
                'nav.friends': 'Друзья',
                'nav.tasks': 'Задания',
                'nav.profile': 'Профиль',
                'status.milk': 'МОЛОКО',
                'status.eggs': 'ЯЙЦА',
                'status.crystal': 'КРИСТАЛЛ',
                'status.deposit': 'Депозит',
                'farm.cow.name': 'Корова',
                'farm.chicken.name': 'Курица',
                'farm.crystal.name': 'Кристальный двигатель',
                'farm.prod': 'Произ',
                'farm.owned': 'Влад',
                'farm.supply': 'Предл',
                'farm.buy': 'Купить несколько',
                'farm.hatch': 'Вывести',
                'farm.start': 'Запустить',
                'farm.yield': 'Выход',
                'market.title': 'P2P Рынок',
                'market.buy': 'Купить',
                'market.myOrders': 'Мои заказы',
                'market.milk': 'Молоко',
                'market.eggs': 'Яйца',
                'market.totalOrders': 'Всего',
                'market.milkQty': 'Молоко',
                'market.eggsQty': 'Яйца',
                'market.bestPrice': 'Лучшая цена',
                'market.createSell': 'Создать ордер',
                'market.refresh': 'Обновить',
                'market.loadMore': 'Показать еще',
                'market.noOrders': 'Нет активных ордеров',
                'market.activeOrders': 'Активные',
                'market.history': 'История',
                'crystal.title': 'Конвертация кристаллов',
                'crystal.perTon': 'TON за кристалл',
                'crystal.yourCrystals': 'Ваши кристаллы',
                'crystal.youReceive': 'Вы получите',
                'crystal.convert': 'Конвертировать',
                'crystal.milkAvailable': 'Молоко доступно',
                'crystal.eggsAvailable': 'Яйца доступны',
                'referral.title': 'Реферальная программа',
                'referral.description': 'Зарабатывайте 10% комиссии, когда ваши друзья покупают машины!',
                'referral.share': 'Поделитесь этой ссылкой с друзьями',
                'referral.friends': 'Друзей',
                'referral.claim': 'Забрать доход',
                'referral.recent': 'Недавние рефералы',
                'referral.noReferrals': 'Пока нет рефералов',
                'referral.earningsHistory': 'История доходов',
                'referral.noEarnings': 'Пока нет доходов',
                'tasks.title': 'Задания и награды',
                'tasks.partner': 'Партнерские',
                'tasks.community': 'Сообщества',
                'tasks.addTask': 'Добавить задание',
                'tasks.refresh': 'Обновить',
                'tasks.noTasks': 'Нет доступных заданий',
                'tasks.taskType': 'Тип задания',
                'tasks.channel': 'Канал',
                'tasks.bot': 'Бот',
                'tasks.channelNote': '⚠️ Бот должен быть администратором канала!',
                'tasks.link': 'Ссылка',
                'tasks.targetUsers': 'Цель (мин 100)',
                'tasks.rewardPerUser': 'Награда за пользователя',
                'tasks.rewardFixed': 'Фиксировано 0.001 TON',
                'tasks.yourBalance': 'Ваш баланс',
                'tasks.confirm': 'Подтвердить и оплатить',
                'tasks.verify': 'Проверка задания',
                'tasks.join': 'Присоединиться',
                'tasks.check': 'Проверить и получить',
                'tasks.reward': 'Награда',
                'profile.totalMachines': 'Всего машин',
                'profile.production': 'Производство',
                'profile.assets': 'Активы',
                'profile.balance': 'Баланс',
                'profile.withdraw': 'Вывести TON',
                'profile.withdrawAmount': 'Сумма (мин 0.1 TON)',
                'profile.withdrawAddress': 'TON адрес кошелька',
                'profile.fee': 'Комиссия (5%)',
                'profile.youReceive': 'Вы получите',
                'profile.withdrawBtn': 'Вывести',
                'modal.sell.title': 'Ордер на продажу',
                'modal.sell.resource': 'Ресурс',
                'modal.sell.quantity': 'Количество (мин 100)',
                'modal.sell.place': 'Разместить ордер',
                'modal.confirm.title': 'Подтверждение покупки',
                'modal.confirm.package': 'Пакет молока',
                'modal.confirm.cancel': 'Отмена',
                'modal.confirm.confirm': 'Подтвердить и оплатить',
                'modal.hatch.title': 'Вывести машину',
                'modal.hatch.cowCost': '50,000 Молока',
                'modal.hatch.chickenCost': '5,000 Яиц',
                'modal.hatch.hatchBtn': 'Вывести',
                'modal.deposit.title': 'Депозит TON',
                'modal.deposit.wallet': 'Кошелек',
                'modal.deposit.notConnected': 'Не подключен',
                'modal.deposit.connect': 'Подключить',
                'modal.deposit.important': 'ВАЖНО:',
                'modal.deposit.warning': 'Ваш User ID',
                'modal.deposit.mustBeComment': 'должен быть ЕДИНСТВЕННЫМ комментарием',
                'modal.deposit.amount': 'Сумма (TON)',
                'modal.deposit.submit': 'Депозит TON',
                'modal.deposit.processing': 'Обработка депозита...',
                'help.title': 'Как играть',
                'help.cow.title': 'Корова',
                'help.cow.desc': '1 TON · 41 Молоко/час<br>Всего: 1000 машин<br>Вывод: 50,000 Молока = 1 Корова',
                'help.chicken.title': 'Курица',
                'help.chicken.desc': '1 TON · 41 Яйца/час<br>Открывается после всех коров',
                'help.crystal.title': 'Кристальный двигатель',
                'help.crystal.desc': '20 TON · 20k Молока + 20k Яиц = 1 Кристалл<br>Конвертация в TON',
                'help.hatch.title': 'Система вывода',
                'help.hatch.desc': '50,000 Молока = 1 Корова<br>5,000 Яиц = 1 Курица<br>Без лимита',
                'help.market.title': 'P2P Рынок',
                'help.market.desc': 'Торгуйте молоком и яйцами',
                'help.referral.title': 'Рефералы',
                'help.referral.desc': '10% от покупок друзей',
                'help.tasks.title': 'Задания',
                'help.tasks.desc': 'Выполняйте задания за 0.001 TON',
                'help.leaderboard.title': 'Соревнование',
                'help.leaderboard.desc': '1 новая корова = 10 очков · Топ-20 выигрывают 150 TON<br>Заканчивается когда продано 1000 коров'
            }
        };

        const LEADERBOARD_INFO_TRANSLATIONS = {
            en: {
                title: '🏆 How does the competition work?',
                grandPrize: '🏆 Grand Prize',
                totalPrize: 'Total prize pool 150 TON distributed to top 20 players',
                howToParticipate: '🐮 How to participate?',
                howToDesc: 'Each new cow you buy = 10 points<br>You must buy at least one cow to appear',
                whenEnds: '⏰ When does it end?',
                whenDesc: 'The competition ends when 1000 cows are sold',
                gotIt: '✅ Got it',
                prizeList: [
                    { rank: '1st', prize: '40 TON' },
                    { rank: '2nd', prize: '30 TON' },
                    { rank: '3rd', prize: '20 TON' },
                    { rank: '4th', prize: '10 TON' },
                    { rank: '5th', prize: '8 TON' },
                    { rank: '6th', prize: '6 TON' },
                    { rank: '7th', prize: '5 TON' },
                    { rank: '8th', prize: '4 TON' },
                    { rank: '9th-10th', prize: '3 TON' },
                    { rank: '11th-18th', prize: '2 TON' },
                    { rank: '19th-20th', prize: '1 TON' }
                ]
            },
            ru: {
                title: '🏆 Как работает соревнование?',
                grandPrize: '🏆 Главный приз',
                totalPrize: 'Общий призовой фонд 150 TON распределяется между топ-20 игроками',
                howToParticipate: '🐮 Как участвовать?',
                howToDesc: 'Каждая новая купленная корова = 10 очков<br>Вы должны купить хотя бы одну корову, чтобы появиться',
                whenEnds: '⏰ Когда заканчивается?',
                whenDesc: 'Соревнование заканчивается, когда продано 1000 коров',
                gotIt: '✅ Понятно',
                prizeList: [
                    { rank: '1 место', prize: '40 TON' },
                    { rank: '2 место', prize: '30 TON' },
                    { rank: '3 место', prize: '20 TON' },
                    { rank: '4 место', prize: '10 TON' },
                    { rank: '5 место', prize: '8 TON' },
                    { rank: '6 место', prize: '6 TON' },
                    { rank: '7 место', prize: '5 TON' },
                    { rank: '8 место', prize: '4 TON' },
                    { rank: '9-10 место', prize: '3 TON' },
                    { rank: '11-18 место', prize: '2 TON' },
                    { rank: '19-20 место', prize: '1 TON' }
                ]
            }
        };

        // ==================== APP STATE ====================
        let App = {
            userId: null,
            user: null,
            global: null,
            constants: null,
            referral: null,
            market: null,
            tasks: null,
            leaderboard: null,
            ranch: {
                cowLevels: { 1: 0, 2: 0, 3: 0 },
                cowActive: { 1: 0, 2: 0, 3: 0 },
                cowActiveUntil: {},
                milkStored: 0,
                storageLevel: 1,
                storageCapacity: 2000,
                hourlyProduction: 0
            },
            telegram: null,
            wallet: null,
            tonConnectUI: null,
            timerInterval: null,
            marketInterval: null,
            depositCheckInterval: null,
            currentMarketResource: 'milk',
            currentMarketPage: 1,
            hasMoreOrders: false,
            currentDepositId: null,
            currentTxHash: null,
            pendingOrder: null,
            pendingTask: null,
            currentLanguage: 'en',
            referralsPage: 1,
            earningsPage: 1,
            hasMoreReferrals: false,
            hasMoreEarnings: false,
            currentTaskTab: 'partner',
            currentActivateLevel: 1,
            currentUpgradeFromLevel: 1,
            initialized: false
        };

        const lastClickTimers = {};
        const CLICK_COOLDOWN = 3000;

        // ==================== UTILITIES ====================
